#!/usr/bin/env node
/**
 * End-to-end tests for the profile README.
 *
 * Run: node tests/readme.e2e.mjs
 *
 * Three layers, all run against the real artefacts:
 *   1. Source contract  - the markup rules that make the page responsive.
 *   2. Render           - GitHub's own Markdown API renders README.md, and the
 *                         resulting HTML is inspected (this is what visitors
 *                         actually get, sanitiser included).
 *   3. Live assets      - every image URL is fetched; a card that 404s or
 *                         returns an error SVG is a failure, because a broken
 *                         card collapses the layout.
 *
 * Layers 2 and 3 need network access. `--offline` skips them.
 */

import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OFFLINE = process.argv.includes("--offline");
const USER = "syedprogg";

/** URLs expected to 404 until a prerequisite has run; reported as WARN, not FAIL. */
const PENDING = [
  {
    match: /\/output\/snake(-dark)?\.svg$/,
    why: "generated by .github/workflows/snake.yml; 404s until that workflow has run once",
  },
];

const results = [];
const check = (name, fn) => results.push({ name, fn });
const assert = (cond, msg) => {
  if (!cond) throw new Error(msg);
};

const readme = await readFile(join(ROOT, "README.md"), "utf8");

/* ------------------------------------------------------------------ *
 * 1. Source contract
 * ------------------------------------------------------------------ */

// Strip HTML comments; the TODO blocks contain example markup on purpose.
const body = readme.replace(/<!--[\s\S]*?-->/g, "");
const imgTags = [...body.matchAll(/<img\b[^>]*>/gi)].map((m) => m[0]);
const widthOf = (tag) => (tag.match(/\bwidth\s*=\s*"([^"]+)"/i) || [])[1];
const srcOf = (tag) => (tag.match(/\b(?:src|srcset)\s*=\s*"([^"]+)"/i) || [])[1];

check("every sized image uses a percentage width, never pixels", () => {
  const offenders = imgTags
    .map((t) => [srcOf(t), widthOf(t)])
    .filter(([, w]) => w !== undefined && !w.endsWith("%"));
  assert(
    offenders.length === 0,
    `pixel/unitless widths force horizontal scroll on phones: ${JSON.stringify(offenders)}`,
  );
});

check("no fixed-width table layout wraps the cards", () => {
  assert(
    !/<t(able|d|r)\b/i.test(body),
    "table-based columns were the original cause of the ~900px minimum width",
  );
});

check("no inline style attributes (GitHub's sanitiser strips them)", () => {
  assert(
    !/\bstyle\s*=\s*"/i.test(body),
    "style= is removed by GitHub, so any layout relying on it silently breaks",
  );
});

// Measured in Chrome against GitHub's own rendering: in a 343 px phone column
// a card at width="48%" lands at ~165 px, a 0.41 scale that drops the card's
// ~14 px text to about 6 px. github-readme-stats clamps `card_width`
// server-side, so no narrower source exists to swap in via <picture>, and
// GitHub strips <style>, so there are no breakpoints to work with. One card
// per row at 100% is therefore the only legible mobile layout.
check("cards sit one per row at full width, so phone text stays legible", () => {
  for (const [, block] of body.matchAll(/<p align="center">([\s\S]*?)<\/p>/gi)) {
    const sized = [...block.matchAll(/<img\b[^>]*>/gi)]
      .map((m) => [srcOf(m[0]), widthOf(m[0])])
      .filter(([, w]) => w !== undefined);
    if (sized.length === 0) continue;
    assert(
      sized.length === 1,
      `${sized.length} sized images share one row; each would render at ~1/${sized.length} scale on a phone`,
    );
    assert(
      parseFloat(sized[0][1]) === 100,
      `${sized[0][0]} is ${sized[0][1]} wide; a lone card should fill the column at 100%`,
    );
  }
});

check("HTML tags are balanced", () => {
  const stack = [];
  const void_ = new Set(["img", "br", "hr", "source", "input", "meta"]);
  for (const [, closing, name] of body.matchAll(/<(\/?)([a-z0-9]+)\b[^>]*?(\/?)>/gi)) {
    const tag = name.toLowerCase();
    if (void_.has(tag)) continue;
    if (closing) {
      assert(stack.pop() === tag, `unbalanced </${tag}> (stray closing tag)`);
    } else {
      stack.push(tag);
    }
  }
  assert(stack.length === 0, `unclosed tags: ${stack.join(", ")}`);
});

check("all stats and card URLs point at the right account", () => {
  const stray = [...body.matchAll(/https?:\/\/[^"\s)]+/g)]
    .map((m) => m[0])
    .filter((u) => /github-readme-stats|githubusercontent|komarev|snk/i.test(u))
    .filter((u) => !u.includes(USER));
  assert(stray.length === 0, `data URLs not scoped to ${USER}: ${JSON.stringify(stray)}`);
});

check("every image has non-empty alt text", () => {
  const bad = imgTags.filter((t) => !/\balt\s*=\s*"[^"]+"/i.test(t)).map(srcOf);
  assert(bad.length === 0, `missing alt text: ${JSON.stringify(bad)}`);
});

check("the snake honours light and dark colour schemes", () => {
  assert(/<picture>/i.test(body), "no <picture> element");
  assert(
    /prefers-color-scheme: dark/i.test(body) && /prefers-color-scheme: light/i.test(body),
    "both colour-scheme sources must be present",
  );
  assert(
    /<picture>[\s\S]*?<img\b[\s\S]*?<\/picture>/i.test(body),
    "<picture> needs a plain <img> fallback or nothing renders",
  );
});

check("the snake workflow that feeds the README exists", async () => {
  const wf = await readFile(join(ROOT, ".github/workflows/snake.yml"), "utf8");
  const branch = (wf.match(/target_branch:\s*(\S+)/) || [])[1];
  assert(branch, "workflow does not declare a target_branch");
  assert(
    body.includes(`/${USER}/${USER}/${branch}/snake.svg`),
    `README points at a branch the workflow does not publish to (expected ${branch})`,
  );
  for (const name of ["snake.svg", "snake-dark.svg"]) {
    assert(wf.includes(name), `workflow does not generate ${name}, but the README uses it`);
  }
});

/* ------------------------------------------------------------------ *
 * 2. Render through GitHub's own Markdown pipeline
 * ------------------------------------------------------------------ */

let rendered = null;

check("GitHub renders the README without dropping the cards", async () => {
  if (OFFLINE) return "skipped (--offline)";
  const { stdout } = await execFileAsync(
    "gh",
    ["api", "--method", "POST", "/markdown", "-f", "mode=gfm", "-f", `text=${readme}`],
    { maxBuffer: 10 * 1024 * 1024 },
  );
  rendered = stdout;
  const survived = [...rendered.matchAll(/<img\b[^>]*>/gi)];
  assert(
    survived.length >= imgTags.length,
    `${imgTags.length} images in source, only ${survived.length} survived GitHub's sanitiser`,
  );
  const kept = survived.filter((m) => /\bwidth="\d+(\.\d+)?%"/i.test(m[0])).length;
  assert(kept > 0, "percentage widths were stripped by the sanitiser");
  return `${survived.length} images rendered, ${kept} with percentage widths`;
});

check("rendered HTML contains no fixed-width container", () => {
  if (OFFLINE || !rendered) return "skipped (no rendered HTML)";
  assert(!/width="\d+"(?!%)/.test(rendered), "a pixel width survived into the rendered output");
  assert(!/<table/i.test(rendered), "a table survived into the rendered output");
});

/* ------------------------------------------------------------------ *
 * 3. Live assets
 * ------------------------------------------------------------------ */

const urls = [...new Set([...body.matchAll(/(?:src|srcset)="(https?:\/\/[^"]+)"/gi)].map((m) => m[1]))];

check(`all ${urls.length} image URLs return a real image`, async () => {
  if (OFFLINE) return "skipped (--offline)";
  const failures = [];
  const warnings = [];
  await Promise.all(
    urls.map(async (url) => {
      let res;
      try {
        res = await fetch(url, { headers: { "User-Agent": "readme-e2e" } });
      } catch (e) {
        failures.push(`${url} -> ${e.message}`);
        return;
      }
      const pending = PENDING.find((p) => p.match.test(url));
      if (!res.ok) {
        (pending ? warnings : failures).push(
          `${url} -> HTTP ${res.status}${pending ? ` (${pending.why})` : ""}`,
        );
        return;
      }
      const type = res.headers.get("content-type") || "";
      if (!/image\//.test(type)) {
        failures.push(`${url} -> content-type ${type}`);
        return;
      }
      // github-readme-stats answers 200 with an error card when a repo is
      // missing or private; that renders as a broken-looking box.
      if (/github-readme-stats/.test(url)) {
        const text = await res.text();
        if (/Something went wrong|Error|not found|Maximum retries/i.test(text)) {
          failures.push(`${url} -> error card: ${(text.match(/>([^<]{5,80})</) || [])[1]?.trim()}`);
        }
      }
    }),
  );
  for (const w of warnings) console.log(`      WARN  ${w}`);
  assert(failures.length === 0, `\n      - ${failures.join("\n      - ")}`);
  return `${urls.length - warnings.length} ok, ${warnings.length} pending`;
});

/* ------------------------------------------------------------------ *
 * Runner
 * ------------------------------------------------------------------ */

let failed = 0;
console.log(`\nREADME end-to-end suite${OFFLINE ? " (offline)" : ""}\n`);
for (const { name, fn } of results) {
  try {
    const note = await fn();
    console.log(`  PASS  ${name}${note ? `  — ${note}` : ""}`);
  } catch (e) {
    failed++;
    console.log(`  FAIL  ${name}\n        ${e.message}`);
  }
}
console.log(`\n${results.length - failed}/${results.length} passed\n`);
process.exit(failed ? 1 : 0);
